
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jan 06 18:24:26 IST 2016
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final Integer VAL = 17;
  public static final Integer WHEN = 26;
  public static final Integer CONST = 4;
  public static final Integer CASE = 3;
  public static final Integer RCBRECKET = 40;
  public static final Integer INT = 10;
  public static final Integer DECLIST = 37;
  public static final Integer FOR = 8;
  public static final Integer SEMICOLON = 25;
  public static final Integer OROP = 35;
  public static final Integer COMMA = 18;
  public static final Integer MULOP = 32;
  public static final Integer ADDLOP = 31;
  public static final Integer RBRECKET = 38;
  public static final Integer NUM = 27;
  public static final Integer TILL = 28;
  public static final Integer MAIN = 12;
  public static final Integer IF = 9;
  public static final Integer RELOP = 30;
  public static final Integer EOF = 0;
  public static final Integer error = 1;
  public static final Integer START = 20;
  public static final Integer BREAK = 2;
  public static final Integer LCBRECKET = 41;
  public static final Integer ADDOP = 29;
  public static final Integer ASSIGNOP = 34;
  public static final Integer REAL = 14;
  public static final Integer COLON = 19;
  public static final Integer RVAL = 16;
  public static final Integer ELSE = 7;
  public static final Integer ANDOP = 36;
  public static final Integer READ = 15;
  public static final Integer WHILE = 24;
  public static final Integer DEFAULT = 5;
  public static final Integer THEN = 21;
  public static final Integer TRATS = 22;
  public static final Integer VAR = 23;
  public static final Integer LBRECKET = 39;
  public static final Integer PRINT = 13;
  public static final Integer DO = 6;
  public static final Integer IVAL = 11;
  public static final Integer FACTORIAL = 33;
}

